<?php
/**
 * Extension for Simpla
 * File is autogenerated 01.10.2021 17:01:57 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class AuthCodes extends Simpla
{
    public function find_code($phone)
    {
    	$clear_phone = $this->users->clear_phone($phone);
        
    	$query = $this->db->placehold("
            SELECT code
            FROM __authcodes
            WHERE phone = ?
            ORDER BY id DESC
            LIMIT 1
        ", $clear_phone);
        $this->db->query($query);
        
        $code = $this->db->result('code');
        
        return $code;
    }
    

	public function get_authcode($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __authcodes
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_authcodes($filter = array())
	{
		$id_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __authcodes
            WHERE 1
                $id_filter
				$keyword_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_authcodes($filter = array())
	{
        $id_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __authcodes
            WHERE 1
                $id_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_authcode($authcode)
    {
   	    $authcode = (array)$authcode;
        
        if (isset($authcode['phone']))
            $authcode['phone'] = $this->users->clear_phone($authcode['phone']);
        
        if (!isset($authcode['created']))
            $authcode['created'] = date('Y-m-d H:i:s');
        
        $query = $this->db->placehold("
            INSERT INTO __authcodes SET ?%
        ", $authcode);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_authcode($id, $authcode)
    {
   	    $authcode = (array)$authcode;
        
        if (isset($authcode['phone']))
            $authcode['phone'] = $this->users->clear_phone($authcode['phone']);

		$query = $this->db->placehold("
            UPDATE __authcodes SET ?% WHERE id = ?
        ", (array)$authcode, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_authcode($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __authcodes WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }
}