<?php
/**
 * Extension for Simpla
 * File is autogenerated 29.06.2021 8:49:16 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Events extends Simpla
{
	public const ORDER_CD_DISABLED = 10;
	public const ORDER_CD_ENABLED = 11;
	public const ACCEPT_CD_DISABLED = 12;
	public const ACCEPT_CD_ENABLED = 13;
    
    public function get_event($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __events
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_events($filter = array())
	{
		$id_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __events
            WHERE 1
                $id_filter
				$keyword_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_events($filter = array())
	{
        $id_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __events
            WHERE 1
                $id_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_event($event)
    {
		$query = $this->db->placehold("
            INSERT INTO __events SET ?%
        ", (array)$event);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_event($id, $event)
    {
		$query = $this->db->placehold("
            UPDATE __events SET ?% WHERE id = ?
        ", (array)$event, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_event($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __events WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }
}