<?php
/**
 * Extension for Simpla
 * File is autogenerated 05.02.2021 8:47:52 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class PaymentExitpools extends Simpla
{
	public function get_variant($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __payment_exitpool_variants
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_variants($filter = array())
	{
		$id_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __payment_exitpool_variants
            WHERE 1
                $id_filter
				$keyword_filter
            ORDER BY position ASC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_variants($filter = array())
	{
        $id_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __payment_exitpool_variants
            WHERE 1
                $id_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_variant($variant)
    {
		$query = $this->db->placehold("
            INSERT INTO __payment_exitpool_variants SET ?%
        ", (array)$variant);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_variant($id, $variant)
    {
		$query = $this->db->placehold("
            UPDATE __payment_exitpool_variants SET ?% WHERE id = ?
        ", (array)$variant, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_variant($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __payment_exitpool_variants WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }
    
    
    
	public function get_exitpool($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __payment_exitpools
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_exitpools($filter = array())
	{
		$id_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __payment_exitpools
            WHERE 1
                $id_filter
 	           $keyword_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_exitpools($filter = array())
	{
        $id_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __payment_exitpools
            WHERE 1
                $id_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_exitpool($exitpool)
    {
		$query = $this->db->placehold("
            INSERT INTO __payment_exitpools SET ?%
        ", (array)$exitpool);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_exitpool($id, $exitpool)
    {
		$query = $this->db->placehold("
            UPDATE __payment_exitpools SET ?% WHERE id = ?
        ", (array)$exitpool, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_exitpool($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __payment_exitpools WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }
}