<?php

/**
 * Extension for Simpla
 * File is autogenerated 16.11.2021 12:31:36 by CRUD
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Tasks extends Simpla {

    public function get_current_pr_task($number, $task_date) {
        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks
            WHERE number = ?
            AND task_date = ?
        ", $number, $task_date);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

    public function get_current_pr_task_by_balance_id($balance_id, $task_date) {
        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks
            WHERE user_balance_id = ?
            AND task_date = ?
        ", $balance_id, $task_date);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

    public function get_pr_task($id) {
        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks
            WHERE id = ?
        ", (int) $id);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

    public function get_pr_tasks($filter = array()) {
        $id_filter = '';
        $manager_id_filter = '';
        $task_date = '';
        $period_filter = '';
        $status_filter = '';
        $keyword_filter = '';
        $limit = 1000;
        $page = 1;

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array) $filter['id']));

        if (!empty($filter['manager_id']))
            $manager_id_filter = $this->db->placehold("AND manager_id IN (?@)", array_map('intval', (array) $filter['manager_id']));

        if (!empty($filter['task_date']))
            $task_date = $this->db->placehold("AND task_date = ?", $filter['task_date']);

        if (!empty($filter['status']))
            $status_filter = $this->db->placehold("AND status IN (?@)", array_map('intval', (array) $filter['status']));

        if (!empty($filter['period']))
            $period_filter = $this->db->placehold("AND period = ?", $filter['period']);

        if (isset($filter['keyword'])) {
            $keywords = explode(' ', $filter['keyword']);
            foreach ($keywords as $keyword)
                $keyword_filter .= $this->db->placehold('AND (name LIKE "%' . $this->db->escape(trim($keyword)) . '%" )');
        }

        if (isset($filter['limit']))
            $limit = max(1, intval($filter['limit']));

        if (isset($filter['page']))
            $page = max(1, intval($filter['page']));

        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page - 1) * $limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks
            WHERE 1
                $id_filter
                $manager_id_filter
				$task_date
                $period_filter
                $status_filter
                $keyword_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();

        return $results;
    }

    public function count_pr_tasks($filter = array()) {
        $id_filter = '';
        $manager_id_filter = '';
        $task_date = '';
        $period_filter = '';
        $status_filter = '';
        $keyword_filter = '';

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array) $filter['id']));

        if (!empty($filter['manager_id']))
            $manager_id_filter = $this->db->placehold("AND manager_id IN (?@)", array_map('intval', (array) $filter['manager_id']));

        if (!empty($filter['task_date']))
            $task_date = $this->db->placehold("AND task_date = ?", $filter['task_date']);

        if (!empty($filter['status']))
            $status_filter = $this->db->placehold("AND status IN (?@)", array_map('intval', (array) $filter['status']));

        if (!empty($filter['period']))
            $period_filter = $this->db->placehold("AND period = ?", $filter['period']);

        if (isset($filter['keyword'])) {
            $keywords = explode(' ', $filter['keyword']);
            foreach ($keywords as $keyword)
                $keyword_filter .= $this->db->placehold('AND (name LIKE "%' . $this->db->escape(trim($keyword)) . '%" )');
        }

        $query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __pr_tasks
            WHERE 1
                $id_filter
                $manager_id_filter
                $task_date
                $period_filter
                $status_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');

        return $count;
    }

    public function add_pr_task($pr_task) {
        $query = $this->db->placehold("
            INSERT INTO __pr_tasks SET ?%
        ", (array) $pr_task);
        $this->db->query($query);
        $id = $this->db->insert_id();

        return $id;
    }

    public function addMyTask($data) {
        $query = $this->db->placehold("
            INSERT INTO __myTasks SET ?%
        ", (array) $data);
        $this->db->query($query);
        $id = $this->db->insert_id();
        return $id;
    }

    public function update_pr_task($id, $pr_task) {
        $query = $this->db->placehold("
            UPDATE __pr_tasks SET ?% WHERE id = ?
        ", (array) $pr_task, (int) $id);
        $this->db->query($query);

        return $id;
    }

    public function delete_pr_task($id) {
        $query = $this->db->placehold("
            DELETE FROM __pr_tasks WHERE id = ?
        ", (int) $id);
        $this->db->query($query);
    }

}
